### ISSUE TITLE
Temperature conversion should be F not C on battery page.

### ISSUE THREAD

**Issue by smpltechno** [Sleeper85/esphome-yambms#13]
Pretty sure these should all be F not C:, we are in winter here, should be cold.
![image](https://github.com/user-attachments/assets/69deaf7b-d4a5-4d69-b7fe-4a79fc994aed)

These others look good-
![image](https://github.com/user-attachments/assets/06173839-b096-4117-b835-50fa78584661)

**Comment by Sleeper85** [comment]
The YAML dashboard is in `°C` by default.
You simply need to do a search and replace the text `°C` with `°F` in your YAML.
