### ISSUE TITLE
[JK-PB] Auto CCL and OVPR issue (Is correct that CCL=0.0A)

### ISSUE THREAD

**Issue by txubelaxu** [Sleeper85/esphome-yambms#5]
![image](https://github.com/user-attachments/assets/ba73b61a-518b-4880-9d56-c18f4af98b3c)

_Originally posted by @txubelaxu in https://github.com/Sleeper85/esphome-yambms/issues/4#issuecomment-2453557685_

**Comment by Sleeper85** [comment]
Please read :

[Max current](https://github.com/Sleeper85/esphome-yambms/blob/main/documents/README/YamBMS_functions.md#max-current-)

[Requested values](https://github.com/Sleeper85/esphome-yambms/blob/main/documents/README/YamBMS_functions.md#requested-values)

[Auto CCL function](https://github.com/Sleeper85/esphome-yambms/blob/main/documents/README/YamBMS_functions.md#auto-ccl--dcl)

Be careful, the `Auto CCL` function can have an impact on what is requested from your inverter.
I advise you not to activate it to check that everything is working well.

**Comment by Sleeper85** [comment]
Can you install the `YamBMS` dashboard and show me the part I have framed in pink?

![image](https://github.com/user-attachments/assets/842049d7-f473-464f-9e8f-c9be894a3efe)

**Comment by txubelaxu** [comment]
This is with jk-bms-can version (is the version I have running now):
![image](https://github.com/user-attachments/assets/19b992d3-e808-42b2-ac33-9baedd741eae)

**Comment by txubelaxu** [comment]
![image](https://github.com/user-attachments/assets/9a0a596b-bfe2-49bc-b088-951eea8cbd24)

**Comment by Sleeper85** [comment]
How are the settings below set?

![image](https://github.com/user-attachments/assets/f82643ec-4b28-4475-af76-d1c0c092de3f)

![image](https://github.com/user-attachments/assets/cb8de305-817c-4298-9099-f644ad9fe516)

**Comment by Sleeper85** [comment]
This is an old version, please use `YamBMS 1.4.5`

**Comment by txubelaxu** [comment]
Yes, I know. But it is the only version that does not restarts the system 1 time per 3 minutes.
The YamBMS 1.4.5 restarts each 3 minutes and the inverters detects low battery, inverters' relays start "jumping" and sometimes the powersource goes down.
Sorry, but the only stable for me is not the last one.

I would like to use the last one, of course. It is why I am debugging the code.

**Comment by Sleeper85** [comment]
Ok then we will come back to this problem later.

**Comment by txubelaxu** [comment]
Yes, it was because the settings were wrong: I had activated "auto" settings.

Deactivating them, CCL that appears in Victron console is correct.

**Comment by Sleeper85** [comment]
Normally `Auto CCL` reduces the current to `0 A` only if `max_cell_v` reaches or exceeds the `OVPR` voltage you have configured in your BMS.

Maybe this shows an unbalanced battery or a very low `OVPR` voltage?

**Comment by txubelaxu** [comment]
I have to inspect with more detail. 
But I have a OVPR= 3.448V and all the cells are about 3.315V on both BMSs. 
Delta is < 0.005V

**Comment by Sleeper85** [comment]
> I have to inspect with more detail. But I have a OVPR= 3.448V and all the cells are about 3.315V on both BMSs. Delta is < 0.005V

Your OVPR is very low.

What is your `bulk_cell_v`?

I charge my cells at `3.45V` my OVPR is `3.55V` and my OVP `3.65V`.

**Comment by MrPabloUK** [comment]
Yes, the logic for the AutoCVL will not work correctly if bulk voltage is higher than OVPR.
It's not something I would expect to see, especially if the OVP value is set to 3.65v.

In this case, I would increase the value of OVPR to something like 3.60v, or even 3.55v if preferred.

**Comment by Sleeper85** [comment]
Will be added in the doc.

> [!IMPORTANT]  
> The `Auto CCL` function uses the `OVPR` value of your BMS which must be higher than `cell_bulk_voltage` to work properly. `e.g. for LFP` : CVL=3.45V / OVPR=3.55V / OVP=3.65V.
> The `Auto DCL` function uses the `UVPR` value of your BMS. `e.g. for LFP` : UVPR=3.00V

> [!IMPORTANT]  
> The `Auto CVL` function uses the `Balance Trig. Volt.` value of your BMS. `e.g. for LFP` : BTG=0.010V

**Comment by clowrey** [comment]
Maybe the code could even send out an error if the value is higher? Users don't always read docs ;)

**Comment by Sleeper85** [comment]
> Maybe the code could even send out an error if the value is higher? Users don't always read docs ;)

Good idea ;-)

**Comment by Sleeper85** [comment]
> If I am not wrong, in the JK-PB BMSs: OVPR cannot be higher than Bulk Voltage.

Can you check it for us ?

**Comment by MrPabloUK** [comment]
If OVPR can't be set higher than bulk, I can adjust the code to reference the mean of OVPR and OVP.
That should work ok for either type of JK BMS

**Comment by txubelaxu** [comment]
> > If I am not wrong, in the JK-PB BMSs: OVPR cannot be higher than Bulk Voltage.
> 
> Can you check it for us ?

Confirmed: You can see here explained --> https://youtu.be/eZX7CkEEq_8?si=6OH4QK2l22zRvXqQ&t=442

So, OVP > RCV > SOC100% > OVPR > UVPR > SOC0% > UVP

**Comment by Sleeper85** [comment]
Ok Thanks.

We will find another solution to do this.

@MrPabloUK is it possible to use the `balance_trigger_voltage` like you did for `Auto CVL`?

I'm trying to reduce the number of bms sensors needed (I added JDB and Seplos) and I removed `OVP` yesterday because it wasn't used in the code.

**Comment by MrPabloUK** [comment]
Yes, we could use balance trigger voltage.
AutoCCL was originally designed to prevent cell voltage spikes at the end of charging, specifically to avoid hitting OVP.

There's no reason that the AutoCCL couldn't use `cell-bulk_voltage + (10 * balance_trigger_voltage)` as the upper threshold, for example.

In this case, that would be 3.45v + 0.10v = 3.55v (as standard).
The multiplier could be configurable, but 3.55v gives enough headroom for momentary cell voltage spikes.

**Comment by Sleeper85** [comment]
Solved with YamBMS 1.5.1
